replicaCount: 1

image:
  repository: praveen22233/booking-service
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

env:
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
